server:
  port: 8081
  baseUrl: http://localhost:5173
spring:
  datasource:
    username: vue_chart
    password: "000000"
#    url: jdbc:mysql://110.42.96.64:30764/vue_chart
    url: jdbc:mysql://127.0.0.1:3306/vue_chart
logging:
  level:
    sql: debug
